version: "3.9"
services:
  nginx:
    image: 454340114714.dkr.ecr.eu-north-1.amazonaws.com/nginx:${IMAGE_VERSION}
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    links:
      - fpm
  fpm:
    image: 454340114714.dkr.ecr.eu-north-1.amazonaws.com/fpm:${IMAGE_VERSION}
    build: 
      context: .
      dockerfile: ./fpm/Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_NAMES=${DB_NAMES}
      - DB_PASS=${DB_PASS}
