version: "3.9"
#Common behavior of builded
services:
  nginx:
    image: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/nginx:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    links:
      - fpm
  fpm:
    image: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/fpm:${IMAGE_TAG:-latest}
    build: 
      context: .
      dockerfile: ./fpm/Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_NAMES=${DB_NAMES}
      - DB_PASS=${DB_PASS}
