name: Continuous Integration Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup php with composer
        uses: php-actions/composer@v6
      - name: PHPUnit tests
        uses: php-actions/phpunit@master
        with: 
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text
            
  lint:
    name: 'Run lint test'
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          coverage: none
          tools: phpcs
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          php_codesniffer: true
          # Optional: Ignore warnings
          php_codesniffer_args: "-n"
