name: Test .env
on:
  workflow_dispatch:
jobs:
  test:
    environment: staging
    runs-on: ubuntu-latest
    steps: 
        - uses: actions/checkout@v3
        - name: Set ENV
          env:
            DB_USER: ${{ env.DB_USER }}
          run: ./env-test.sh  
        - name: test ENV
          run: echo $DB_USER
