name: Test .env
on:
  workflow_dispatch:
jobs:
  test:
    environment: staging
    runs-on: ubuntu-latest
    env:
      DB_USER: ${{ vars.DB_USER }}
      IMAGE_VERSION: v1
    steps: 
        - uses: actions/checkout@v3
        - name: Set ENV
          run: ./env-test.sh  
        - name: test ENV
          run: echo $DB_USER && cat .env
        - name: install docker compose 
          uses: KengoTODA/actions-setup-docker-compose@v1
          with:
            version: '2.17.3'
        - name: Build and run containers
          run: docker compose up -d --build
        - name: test containers
          run: web/test/check_localhost.sh
